# This file defines some internal variables of this Inspector

# Time delay in seconds to the packet to API
delay: 5
# Location of this Inspector
location: "Entrada principal"
# URL to reach API
url_api: "http://localhost:6000/found"
