# This file defines some internal variables of this Inspector

# Time delay in seconds to send packet to API
delay: 1
# Location of this Inspector
location: "Entrada 3"
# URL to reach API
url_api: "http://34.75.48.156:6000/found"
